### PR TITLE
what4 backend for copilot properties

### PR DESCRIPTION
**Pull request by benjaminselfridge**
This pull request adds partial support for proving stream properties with what4/SMT. It is incomplete, and still needs support for structs & arrays. I'm creating this pull request now so the copilot maintainers can get their eyes on it now.

### CODE REVIEW

**Comment by benjaminselfridge** [comment]
Just finished support for translation of structs and arrays. Could use some feedback whenever possible, we'd love to get these changes pushed through ASAP.

**Comment by ivanperez-keera** [comment]
@benjaminselfridge Just letting you know that I'm looking into merging this ASAP. I'll ping you if there are any questions. Thanks!

**Comment by ivanperez-keera** [comment]
@benjaminselfridge I am stuck here:

```
src/Copilot/Theorem/What4.hs:398:41: error:
    • Could not deduce: ((n1 - 1) + 1) ~ n
      from the context: (a ~ CT.Array n1 t1, KnownNat n1, CT.Typed t1,
                         CT.Typed (CT.InnerType t1), CT.Flatten t1 (CT.InnerType t1))
        bound by a pattern with constructor:
                   CT.Array :: forall (n :: ghc-prim-0.5.3:GHC.Types.Nat) t.
                               (KnownNat n, CT.Typed t, CT.Typed (CT.InnerType t),
                                CT.Flatten t (CT.InnerType t)) =>
                               CT.Type t -> CT.Type (CT.Array n t),
                 in a case alternative
        at src/Copilot/Theorem/What4.hs:393:8-19
      or from: 1 <= n1
        bound by a pattern with constructor:
                   LeqProof :: forall (m :: ghc-prim-0.5.3:GHC.Types.Nat) (n :: ghc-prim-0.5.3:GHC.Types.Nat).
                               (m <= n) =>
                               LeqProof m n,
                 in a case alternative
        at src/Copilot/Theorem/What4.hs:397:13-20
      Expected type: IO (V.Vector n (XExpr t))
        Actual type: IO (V.Vector ((n1 - 1) + 1) (XExpr t))
```

I'm using GHC 8.6.5 at the moment.

Do you know how to prove that type constraint?

EDIT: I can confirm that this compiles with GHC 8.8.4 and the version of what4 available on github. We'll need to add base constraints to the cabal file, or preferably help GHC < 8.8 figure out that (-1 + 1 == 0).

**Comment by benjaminselfridge** [comment]
Thanks for taking a look!

I could look into supporting 8.6 if it's important -- if all that's required is an extra proof, it might be worth it.

I just noticed that you included the word "preferably" to supporting <8.8, so I will take a look at that.

**Comment by benjaminselfridge** [comment]
@ivanperez-keera Did a couple quick fixes for 8.6 compatibility.

**Comment by ivanperez-keera** [comment]
@benjaminselfridge Thanks! Just following up on this. All seems to be working. We have a meeting tomorrow to discuss the merge. I'll keep you posted.

**Comment by benjaminselfridge** [comment]
@ivanperez-keera @agoodloe 

I've opened a PR in `copilot`, where it made more sense (to me) to add what4-specific examples, since they'd be buildable and useable in that repo in a more standalone fashion. If that is okay with you guys, then I think this branch is ready to merge as-is, and we'll just house the examples in `copilot`.

**Comment by fdedden** [comment]
I have added version requirements for the new dependencies, and added 'Refs #9' to every commit message. Thank you for the help!

**Comment by benjaminselfridge** [comment]
Wonderful! Thanks for merging it in.
