### ISSUE TITLE
Failure to compile with GHC 8.6

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot-theorem#3]
The copilot3.0-dev branch fails to compile with GHC 8.6/base-4.12:
```
src/Copilot/Theorem/TransSys/Spec.hs:129:6: error:
    • Data.Map.fold is gone. Use foldr.
```

It compiles fine with GHC 8.4/base-4.11.

**Comment by fdedden** [comment]
A fix has been made in the fold-fix branch: 3de36ac01593b2e9dd55cd2ab9977cc109fd8b5c
Please test again, and merge fold-fix with copilot3.0-dev

**Comment by ivanperez-keera** [comment]
Got it. Thanks!
